name: build-wheel-and-publish-test-pypi


on: push
#  release:
#     # types: [published]


jobs:
  build:
    name: Build distribution
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"

    # - name: Install pypa/build
    #   run: python3 -m pip install build --user  # doesn't function yet
    # - name: Build a binary wheel and a source tarball
    #   run: python3 -m build

    - name: Install pypa/build
      run: >-
        python3 -m
        pip install
        build
        --user
    - name: Build a binary wheel and a source tarball
      run: python3 -m build
    - name: Store the distribution packages
      uses: actions/upload-artifact@v4
      with:
        name: python-package-distributions
        path: dist/

      
  publish-to-testpypi:
    name: Publish imas-data-dictionary distribution to TestPyPI
    needs:
    - build
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish distribution to TestPyPI
      uses: pypa/gh-action-pypi-publish@unstable/v1
      with:
        repository-url: https://test.pypi.org/legacy/
        verbose: true


